/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as proofOfCareSol from "./ProofOfCare.sol";
export { BitheatRegistry__factory } from "./BitheatRegistry__factory";
export { Lock__factory } from "./Lock__factory";
