/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBitheatRegistry } from "./IBitheatRegistry";
export type { ProofOfCare } from "./ProofOfCare";
