/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface BitheatRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "chwZones"
      | "deregisterCHW"
      | "isCHWRegistered"
      | "owner"
      | "registerCHW"
      | "registeredCHWs"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CHWDeregistered"
      | "CHWRegistered"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(functionFragment: "chwZones", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "deregisterCHW",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCHWRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerCHW",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "registeredCHWs",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "chwZones", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deregisterCHW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCHWRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerCHW",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registeredCHWs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace CHWDeregisteredEvent {
  export type InputTuple = [chwDIDHash: BytesLike];
  export type OutputTuple = [chwDIDHash: string];
  export interface OutputObject {
    chwDIDHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CHWRegisteredEvent {
  export type InputTuple = [chwDIDHash: BytesLike, zone: string];
  export type OutputTuple = [chwDIDHash: string, zone: string];
  export interface OutputObject {
    chwDIDHash: string;
    zone: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BitheatRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): BitheatRegistry;
  waitForDeployment(): Promise<this>;

  interface: BitheatRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  chwZones: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  deregisterCHW: TypedContractMethod<
    [chwDIDHash: BytesLike],
    [void],
    "nonpayable"
  >;

  isCHWRegistered: TypedContractMethod<
    [chwDIDHash: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerCHW: TypedContractMethod<
    [chwDIDHash: BytesLike, zone: string],
    [void],
    "nonpayable"
  >;

  registeredCHWs: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "chwZones"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "deregisterCHW"
  ): TypedContractMethod<[chwDIDHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isCHWRegistered"
  ): TypedContractMethod<[chwDIDHash: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerCHW"
  ): TypedContractMethod<
    [chwDIDHash: BytesLike, zone: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registeredCHWs"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CHWDeregistered"
  ): TypedContractEvent<
    CHWDeregisteredEvent.InputTuple,
    CHWDeregisteredEvent.OutputTuple,
    CHWDeregisteredEvent.OutputObject
  >;
  getEvent(
    key: "CHWRegistered"
  ): TypedContractEvent<
    CHWRegisteredEvent.InputTuple,
    CHWRegisteredEvent.OutputTuple,
    CHWRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "CHWDeregistered(bytes32)": TypedContractEvent<
      CHWDeregisteredEvent.InputTuple,
      CHWDeregisteredEvent.OutputTuple,
      CHWDeregisteredEvent.OutputObject
    >;
    CHWDeregistered: TypedContractEvent<
      CHWDeregisteredEvent.InputTuple,
      CHWDeregisteredEvent.OutputTuple,
      CHWDeregisteredEvent.OutputObject
    >;

    "CHWRegistered(bytes32,string)": TypedContractEvent<
      CHWRegisteredEvent.InputTuple,
      CHWRegisteredEvent.OutputTuple,
      CHWRegisteredEvent.OutputObject
    >;
    CHWRegistered: TypedContractEvent<
      CHWRegisteredEvent.InputTuple,
      CHWRegisteredEvent.OutputTuple,
      CHWRegisteredEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
