/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as proofOfCareSol from "./ProofOfCare.sol";
export type { proofOfCareSol };
export type { BitheatRegistry } from "./BitheatRegistry";
export type { Lock } from "./Lock";
