/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IBitheatRegistry,
  IBitheatRegistryInterface,
} from "../../../contracts/ProofOfCare.sol/IBitheatRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "chwDIDHash",
        type: "bytes32",
      },
    ],
    name: "isCHWRegistered",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IBitheatRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IBitheatRegistryInterface {
    return new Interface(_abi) as IBitheatRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IBitheatRegistry {
    return new Contract(address, _abi, runner) as unknown as IBitheatRegistry;
  }
}
