/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBitheatRegistry__factory } from "./IBitheatRegistry__factory";
export { ProofOfCare__factory } from "./ProofOfCare__factory";
